### PR TITLE
icons added to categories

### PR DESCRIPTION
**Pull request by smcqueen-95**
Simulator Screen Shot - iPhone 13 Pro Max - 2022-12-21 at 23 44 33
Simulator Screen Shot - iPhone 13 Pro Max - 2022-12-21 at 23 44 41

### CODE REVIEW

**Review by kpjackson90 — CHANGES_REQUESTED** [review]
Seems like some of these icons are coming outside the tabs, please fix tab sizes so that they can dynamically fit the size of the text and icon

**Comment by smcqueen-95** [comment]
Is this better now? 
Simulator Screen Shot - iPhone 13 Pro Max - 2022-12-22 at 19 01 09
-images.githubusercontent.com/64174106/209239604-9292bc5e-babd-4328-be69-4d60de795e06.png)
@kpjackson90

**Comment by smcqueen-95** [comment]
@kpjackson90 Will continue to use this branch for the functionality as well

**Comment by kpjackson90** [comment]
> 

They still look messed up.

**Pull request merged**
